name: Сборка под Dev

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    uses: OrestMelnyk/my-go-service/.github/workflows/reusable_docker.yml@main
    permissions:
      contents: read
      packages: write
    with:
      image-base-name: ${{ github.repository }}
      deploy-target-name: 'News Out Service'
      compose-service-name: ${{ vars.COMPOSE_SERVICE_NAME }}
      dockerfile-path: './Dockerfile'
      docker-context: '.'
      notify: true
      vds-compose-path: ${{ vars.DEV_VDS_COMPOSE_PATH }}
    secrets:
      ghcr-token: ${{ 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 }}
      vds-host: ${{ 10.0.2.15 }}
      vds-username: ${{ orest }}
      vds-private-key: ${{ ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJTVzUKmNhP/Fo4kgBbmcnyajRBaKzg9B95hpEcafojx orest@archlinux }}
      discord-webhook-url: ${{ https://discordapp.com/api/webhooks/1358726892756406414/WQmmGEVABACU6OE9bn7OFMpruWGifSafWttUDe2JpPPtW3LalitJ93W0m1KCYyTww-Y0 }}
